<<<<<<< ours
[package]
name = "fav-egui"
version = "0.1.0"
edition = "2021"

[dependencies]

|||||||
=======
[package]
name = "fav-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
>>>>>>> theirs
